### PR TITLE
primitive multiply and mdivide_left_tri

### PR DESCRIPTION
**Pull request by rok-cesnovar**
A dummy PR to discuss how we want to handle `prim/multiply` & `prim/mdivide_left_tri` that we would want to merge next as no new kernels need to be added for them to be exposed. 

The only thing left to discuss is what should the default input sizes where we switch to OpenCL be.

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
I looked at multiply first. When you multiply `[N, K] x [K, M`], we create `N x M` threads that each need to perform K products. If `N x M` is low, we dont create enough threads and thus dont use enough of the OpenCL device parallelism. If K is low, each thread does not have enough work to justify its creation and to overcome the data transfer overhead.

I made a [simple test app](https://gist.github.com/rok-cesnovar/ef8827a58abaf14dc257c1dabf2d6eb1) to find the minimum K where an OpenCL device outperforms (speedup = 1.5) the Eigen multiplication of [N, K] x [K, N]. This is the output i7-4790 @ 3.6GHz vs TitanXP. I also ran it on a system with i5-6600 @ 3.50GHz and a AMD R9 Fury and got comparable results.

```
N    min K
150 201
175 183
200 149
250 101
300 73
350 57
400 53
500 39
750 23
1000 17
1100 17
1200 17
1300 17
1400 17
1500 15
1600 15
1700 13
1800 13
```
My proposition would be to switch to OpenCL when NxM > (500*500 = 250000) and K is larger than 100. At this border size, the Titan XP is 3.5x faster than the i7 CPU and I think we are on the safe side with any relevant GPU.

**Comment by rok-cesnovar** [comment]
For mdivide_left_tri(A) these are the Titan XP speedups: 

```
50	0.0242543
100	0.143605
150	0.370872
200	0.849751
250	1.4877
300	1.84792
350	2.68177
400	2.90145
450	4.23558
500	4.97621
550	5.11077
600	6.31694
650	7.24727
700	8.43643
750	8.98316
```
For mdivide_left_tri(A, b) where b is the same size as A these are the Titan XP speedups: 

```
50	0.0234779
100	0.138172
150	0.339177
200	0.639696
250	0.950818
300	1.1729
350	1.72821
400	1.77627
450	2.28321
500	2.8743
550	2.94056
600	3.53811
650	4.07604
700	4.5648
750	4.84352
800	5.57367
850	5.5613
900	5.13805
950	6.24903
```

I think N = 500 could again be the limit in both cases just so that we are on the safe side for any relevant GPU.

**Comment by seantalts** [comment]
I think that's reasonable. How long do these take to run? Would it be worth including code to set these based on benchmarks as a `stan::math::gpu::autotune()` function or something?

**Comment by rok-cesnovar** [comment]
They take up a few seconds, they could be sped up with some bisection logic to avoid this sort of thorough search.

**Comment by SteveBronder** [comment]
Should we be doing `prim/multiply` and `rev/multiply` in the same PR?

Looking at the code for multiply, if we move the `AB` out of the constructor the rev code would pretty much just be

```c++
// ... constructor stuff
matrix_cl AB_adj = Ad_cl * Bd_cl;
matrix_cl A_adj = AB_adj * Bd_cl;
matrix_cl B_adj = transpose(Ad_cl) * AB_adj;
copy(adjA, A_adj);
copy(adjB, B_adj);
/// ... fill in var
    for (size_type i = 0; i < A_size_; ++i)
      variRefA_[i]->adj_ += adjA(i);
    for (size_type i = 0; i < B_size_; ++i)
      variRefB_[i]->adj_ += adjB(i);
```

Could be wrong but it seems like something like that. The code there is kind of weird to me, not sure why things are happening in certain places (like why AB is done in the constructor and not the chain)

**Comment by rok-cesnovar** [comment]
I havent looked into rev/multiply that much, just made a quick and dirty working example with OpenCL, same for rev/mdivide_left_tri but that one needs more work.

This was my idea for the plan on the PRs in the near future: 
1. triangular multiply (opened, needs review)
2. replace triangular multiply in Cholesky prim/rev (finished on the branch, really simple but great performance boost, will open stan math PR once (1.) goes through) https://github.com/bstatcomp/math/tree/gpu-cholesky-triangular-multiply 
3. prim/multiply (ready on the branch of this PR)
4. prim/mdivide_left_tri (ready on the branch of this PR)
5. rev/multiply (works, faster, gross or now)
6. rev/mdivide_left_tri (not ready yet)

2-6 introduce no new OpenCL kernels so they will be easier to review. I was a bit optimistic with hoping to get 1 and 2 in before 2.19, but I guess it will have to wait. I am going to post an issue on this fork on which I will track informally what I am doing.

**Pull request closed without merging**
